version: '3'

services:
  mongo:
    image: mongo
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
    volumes:
      - ./data:/data/db
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_DATABASE=$MONGODB_DATABASE
      - DB_PASSWORD=$MONGODB_ROOT_PASSWORD
      - DB_PORT=$MONGODB_PORT
      - API_PORT=$API_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - $UI_LOCAL_PORT:$UI_DOCKER_PORT
    depends_on:
      - backend