version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_DATABASE=$DB_DATABASE
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - API_PORT=$API_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend